enum Actions {
  ADD_FILM,
  BUY_TICKETS,
  FETCH_FILMS,
  FETCH_SHOWINGS,
  FETCH_THEATER,
  HIDE_FILM_DETAILS,
  SET_CART,
  SET_SELECTED_DATE,
  SET_SELECTED_FILM,
  SET_SELECTED_SHOWING,
  SET_SHOWINGS,
  SET_THEATER,
}
